exports.fields = {
  id: {
    typeVal: 'INTEGER',
    label: 'id',
    dbField: 'id',
    typeDbField: 'INTEGER',
    primaryKey: true,
    foreignKey: false,
    references: '',
    required: true,
    error: false,
    errorMessage: '',
    value: '',
    visible: true,
    editable: true
  },
  modello: {
    typeVal: 'STRING',
    label: 'modello',
    dbField: 'modello',
    typeDbField: 'STRING',
    primaryKey: false,
    foreignKey: false,
    references: '',
    required: true,
    error: false,
    errorMessage: '',
    value: '',
    visible: true,
    editable: true
  },
  marcheId: {
    typeVal: 'INTEGER',
    label: 'marcheId',
    dbField: 'marcheId',
    typeDbField: 'INTEGER',
    primaryKey: false,
    foreignKey: true,
    references: 'marche',
    required: true,
    error: false,
    errorMessage: '',
    value: '',
    visible: true,
    editable: true
  },
  deleted: {
    typeVal: 'INTEGER',
    label: 'deleted',
    dbField: 'deleted',
    typeDbField: 'INTEGER',
    primaryKey: false,
    foreignKey: false,
    references: '',
    required: true,
    error: false,
    errorMessage: '',
    value: '',
    visible: true,
    editable: true
  },
  proprietarioId: {
    typeVal: 'INTEGER',
    label: 'proprietarioId',
    dbField: 'proprietarioId',
    typeDbField: 'INTEGER',
    primaryKey: false,
    foreignKey: true,
    references: 'prova',
    required: true,
    error: false,
    errorMessage: '',
    value: '',
    visible: true,
    editable: true
  }
}